name: xwidgets
channels:
- conda-forge
dependencies:
  # Build dependencies
- cmake <4
- cxx-compiler
- ninja
  # Host dependencies
- xeus>=5.0.0,<6
- xproperty=0.12.1
- nlohmann_json=3.12.0
  # Test dependencies
- doctest >= 2.4.6
- json_schema_validator
- pre-commit
- cmake-format
# Jupyterlite build dependencies
- jupyter_server
- jupyterlite-core
- jupyterlite-xeus
