name: xwidgets
channels:
- conda-forge
dependencies:
  # Build dependencies
- cmake
- cxx-compiler
- ninja
  # Host dependencies
- xeus>=5.0.0,<6
- xproperty=0.11.0
- nlohmann_json=3.11.3
  # Test dependencies
- doctest >= 2.4.6
- json_schema_validator
- pre-commit
- cmake-format
